# Generated by Django 5.2.1 on 2025-05-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_kgs',
            field=models.IntegerField(default=0),
        ),
    ]
